[package]
name = "dvcdbg"
version = "0.1.0"
edition = "2024"

[dependencies]
ufmt = { version = "0.2.0", default-features = false }
heapless = { version = "0.8.0", features = ["boxed"] }

[dev-dependencies]
sh1107g-rs = { path = "../sh1107g-rs" }