[package]
name = "dvcdbg"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-hal = "1.0.0"
heapless = "0.8"

[features]
default = []
debug_log = []

[dev-dependencies]
sh1107g-rs = { path = "../sh1107g-rs", features = ["debug_log"] }