name: Auto Clippy Fix 

on:
  push:
    branches:
      - 'develop/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  clippy-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo clippy and cargo fix
        run: |
          cargo clippy --all-features -- -D warnings
          cargo fix --allow-dirty --allow-staged

          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: automatic clippy fixes"
            git push
          else
            echo "No fixes needed."
          fi
